// apps/demo-angular/src/plugin-demos/nativescript-tracking-transparency.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptTrackingTransparency } from '@demo/shared';
import {} from '@nstudio/nativescript-tracking-transparency';

@Component({
	selector: 'demo-nativescript-tracking-transparency',
	templateUrl: 'nativescript-tracking-transparency.component.html',
})
export class NativescriptTrackingTransparencyComponent {
	demoShared: DemoSharedNativescriptTrackingTransparency;

	constructor(private _ngZone: NgZone) {}

	ngOnInit() {
		this.demoShared = new DemoSharedNativescriptTrackingTransparency();
	}
}

<ActionBar title="nativescript-tracking-transparency" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-tracking-transparency" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>

// apps/demo-svelte/app/plugin-demos/nativescript-tracking-transparency.svelte
<page>
    <actionBar title="nativescript-tracking-transparency" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptTrackingTransparency } from '@demo/shared';
    import { } from '@nstudio/nativescript-tracking-transparency';

    let message: string = "Test nativescript-tracking-transparency"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>
