// apps/demo-angular/src/plugin-demos/nativescript-cardview.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptCardview } from '@demo/shared';
import { } from '@nstudio/nativescript-cardview';

@Component({
	selector: 'demo-nativescript-cardview',
	templateUrl: 'nativescript-cardview.component.html',
})
export class NativescriptCardviewComponent {
  
  demoShared: DemoSharedNativescriptCardview;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptCardview();
  }

}
<ActionBar title="nativescript-cardview" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-cardview" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>

// apps/demo-svelte/app/plugin-demos/nativescript-cardview.svelte
<page>
    <actionBar title="nativescript-cardview" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptCardview } from '@demo/shared';
    import { } from '@nstudio/nativescript-cardview';

    let message: string = "Test nativescript-cardview"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>
