// apps/demo-angular/src/plugin-demos/nativescript-embrace.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptEmbrace } from '@demo/shared';
import { } from '@nstudio/nativescript-embrace';

@Component({
	selector: 'demo-nativescript-embrace',
	templateUrl: 'nativescript-embrace.component.html',
})
export class NativescriptEmbraceComponent {
  
  demoShared: DemoSharedNativescriptEmbrace;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptEmbrace();
  }

}
<ActionBar title="nativescript-embrace" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-embrace" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>

// apps/demo-svelte/app/plugin-demos/nativescript-embrace.svelte
<page>
    <actionBar title="nativescript-embrace" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptEmbrace } from '@demo/shared';
    import { } from '@nstudio/nativescript-embrace';

    let message: string = "Test nativescript-embrace"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>
