// apps/demo-angular/src/plugin-demos/nativescript-barcodescanner.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptBarcodescanner } from '@demo/shared';
import { } from '@nstudio/nativescript-barcodescanner';

@Component({
	selector: 'demo-nativescript-barcodescanner',
	templateUrl: 'nativescript-barcodescanner.component.html',
})
export class NativescriptBarcodescannerComponent {
  
  demoShared: DemoSharedNativescriptBarcodescanner;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptBarcodescanner();
  }

}
<ActionBar title="nativescript-barcodescanner" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-barcodescanner" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>

// apps/demo-svelte/app/plugin-demos/nativescript-barcodescanner.svelte
<page>
    <actionBar title="nativescript-barcodescanner" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptBarcodescanner } from '@demo/shared';
    import { } from '@nstudio/nativescript-barcodescanner';

    let message: string = "Test nativescript-barcodescanner"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>
