// apps/demo-angular/src/plugin-demos/nativescript-walletconnect.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptWalletconnect } from '@demo/shared';
import { } from '@nstudio/nativescript-walletconnect';

@Component({
	selector: 'demo-nativescript-walletconnect',
	templateUrl: 'nativescript-walletconnect.component.html',
})
export class NativescriptWalletconnectComponent {
  
  demoShared: DemoSharedNativescriptWalletconnect;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptWalletconnect();
  }

}
<ActionBar title="nativescript-walletconnect" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-walletconnect" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>

// apps/demo-svelte/app/plugin-demos/nativescript-walletconnect.svelte
<page>
    <actionBar title="nativescript-walletconnect" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptWalletconnect } from '@demo/shared';
    import { } from '@nstudio/nativescript-walletconnect';

    let message: string = "Test nativescript-walletconnect"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>
