// apps/demo-angular/src/plugin-demos/nativescript-splitsheet.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptSplitsheet } from '@demo/shared';
import { } from '@nstudio/nativescript-splitsheet';

@Component({
	selector: 'demo-nativescript-splitsheet',
	templateUrl: 'nativescript-splitsheet.component.html',
})
export class NativescriptSplitsheetComponent {
  
  demoShared: DemoSharedNativescriptSplitsheet;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptSplitsheet();
  }

}
<ActionBar title="nativescript-splitsheet" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-splitsheet" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>

// apps/demo-svelte/app/plugin-demos/nativescript-splitsheet.svelte
<page>
    <actionBar title="nativescript-splitsheet" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptSplitsheet } from '@demo/shared';
    import { } from '@nstudio/nativescript-splitsheet';

    let message: string = "Test nativescript-splitsheet"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>
