// apps/demo-angular/src/plugin-demos/nativescript-carousel.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptCarousel } from '@demo/shared';
import { } from '@nstudio/nativescript-carousel';

@Component({
	selector: 'demo-nativescript-carousel',
	templateUrl: 'nativescript-carousel.component.html',
})
export class NativescriptCarouselComponent {
  
  demoShared: DemoSharedNativescriptCarousel;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptCarousel();
  }

}
<ActionBar title="nativescript-carousel" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-carousel" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>

// apps/demo-svelte/app/plugin-demos/nativescript-carousel.svelte
<page>
    <actionBar title="nativescript-carousel" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptCarousel } from '@demo/shared';
    import { } from '@nstudio/nativescript-carousel';

    let message: string = "Test nativescript-carousel"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>
