// apps/demo-angular/src/plugin-demos/nativescript-airship-adm.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptAirshipAdm } from '@demo/shared';
import { } from '@nstudio/nativescript-airship-adm';

@Component({
	selector: 'demo-nativescript-airship-adm',
	templateUrl: 'nativescript-airship-adm.component.html',
})
export class NativescriptAirshipAdmComponent {
  
  demoShared: DemoSharedNativescriptAirshipAdm;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptAirshipAdm();
  }

}
<ActionBar title="nativescript-airship-adm" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-airship-adm" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>

// apps/demo-svelte/app/plugin-demos/nativescript-airship-adm.svelte
<page>
    <actionBar title="nativescript-airship-adm" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptAirshipAdm } from '@demo/shared';
    import { } from '@nstudio/nativescript-airship-adm';

    let message: string = "Test nativescript-airship-adm"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>
