// apps/demo-angular/src/plugin-demos/nativescript-appcues.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptAppcues } from '@demo/shared';
import { } from '@nstudio/nativescript-appcues';

@Component({
	selector: 'demo-nativescript-appcues',
	templateUrl: 'nativescript-appcues.component.html',
})
export class NativescriptAppcuesComponent {
  
  demoShared: DemoSharedNativescriptAppcues;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptAppcues();
  }

}
<ActionBar title="nativescript-appcues" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-appcues" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>

// apps/demo-svelte/app/plugin-demos/nativescript-appcues.svelte
<page>
    <actionBar title="nativescript-appcues" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptAppcues } from '@demo/shared';
    import { } from '@nstudio/nativescript-appcues';

    let message: string = "Test nativescript-appcues"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>
