// apps/demo-svelte/app/plugin-demos/nativescript-carousel.svelte
<page>
    <actionBar title="nativescript-carousel" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptCarousel } from '@demo/shared';
    import { } from '@nstudio/nativescript-carousel';

    let message: string = "Test nativescript-carousel"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-vue/app/plugin-demos/nativescript-carousel.vue
<template>
  <Page>
    <ActionBar>
      <Label text="nativescript-carousel"/>
    </ActionBar>

    <GridLayout>
      <Button class="info" :text="message"/>
    </GridLayout>
  </Page>
</template>

<script lang="ts">
  import Vue from "nativescript-vue";
  import { DemoSharedNativescriptCarousel } from '@demo/shared';
  import { } from '@nstudio/nativescript-carousel';

  export default Vue.extend({
    computed: {
      message() {
        return "Test nativescript-carousel";
      }
    }
  });
</script>

<style scoped lang="scss">

  .info {
    font-size: 20;
    horizontal-align: center;
    vertical-align: center;
  }
</style>
