// apps/demo-svelte/app/plugin-demos/nativescript-plaid.svelte
<page>
    <actionBar title="nativescript-plaid" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptPlaid } from '@demo/shared';
    import { } from '@nstudio/nativescript-plaid';

    let message: string = "Test nativescript-plaid"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-plaid.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptPlaid } from '@demo/shared';
import {} from '@nstudio/nativescript-plaid';

@Component({
	selector: 'demo-nativescript-plaid',
	templateUrl: 'nativescript-plaid.component.html',
})
export class NativescriptPlaidComponent {
	demoShared: DemoSharedNativescriptPlaid;

	constructor(private _ngZone: NgZone) {}

	ngOnInit() {
		this.demoShared = new DemoSharedNativescriptPlaid();
	}
}

<ActionBar title="nativescript-plaid" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-plaid" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>
