// apps/demo-svelte/app/plugin-demos/nativescript-freshchat.svelte
<page>
    <actionBar title="nativescript-freshchat" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptFreshchat } from '@demo/shared';
    import { } from '@nstudio/nativescript-freshchat';

    let message: string = "Test nativescript-freshchat"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-freshchat.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptFreshchat } from '@demo/shared';
import { } from '@nstudio/nativescript-freshchat';

@Component({
	selector: 'demo-nativescript-freshchat',
	templateUrl: 'nativescript-freshchat.component.html',
})
export class NativescriptFreshchatComponent {
  
  demoShared: DemoSharedNativescriptFreshchat;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptFreshchat();
  }

}
<ActionBar title="nativescript-freshchat" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-freshchat" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>
