// apps/demo-svelte/app/plugin-demos/nativescript-exoplayer.svelte
<page>
    <actionBar title="nativescript-exoplayer" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptExoplayer } from '@demo/shared';
    import { } from '@nstudio/nativescript-exoplayer';

    let message: string = "Test nativescript-exoplayer"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-exoplayer.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptExoplayer } from '@demo/shared';
import { Page } from '@nativescript/core';
import {} from '@nstudio/nativescript-exoplayer';

@Component({
	selector: 'demo-nativescript-exoplayer',
	templateUrl: 'nativescript-exoplayer.component.html',
})
export class NativescriptExoplayerComponent {
	demoShared: DemoSharedNativescriptExoplayer;

	constructor(private _ngZone: NgZone, private _page: Page) {}

	ngOnInit() {
		this.demoShared = new DemoSharedNativescriptExoplayer(this._page);
	}
}

<ActionBar title="nativescript-exoplayer" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-exoplayer" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>
