// apps/demo-svelte/app/plugin-demos/nativescript-aptabase.svelte
<page>
    <actionBar title="nativescript-aptabase" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptAptabase } from '@demo/shared';
    import { } from '@nstudio/nativescript-aptabase';

    let message: string = "Test nativescript-aptabase"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-aptabase.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptAptabase } from '@demo/shared';
import { } from '@nstudio/nativescript-aptabase';

@Component({
	selector: 'demo-nativescript-aptabase',
	templateUrl: 'nativescript-aptabase.component.html',
})
export class NativescriptAptabaseComponent {
  
  demoShared: DemoSharedNativescriptAptabase;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptAptabase();
  }

}
<ActionBar title="nativescript-aptabase" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-aptabase" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>
