// apps/demo-svelte/app/plugin-demos/nativescript-airship-hms.svelte
<page>
    <actionBar title="nativescript-airship-hms" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptAirshipHms } from '@demo/shared';
    import { } from '@nstudio/nativescript-airship-hms';

    let message: string = "Test nativescript-airship-hms"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-airship-hms.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptAirshipHms } from '@demo/shared';
import { } from '@nstudio/nativescript-airship-hms';

@Component({
	selector: 'demo-nativescript-airship-hms',
	templateUrl: 'nativescript-airship-hms.component.html',
})
export class NativescriptAirshipHmsComponent {
  
  demoShared: DemoSharedNativescriptAirshipHms;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptAirshipHms();
  }

}
<ActionBar title="nativescript-airship-hms" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-airship-hms" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>
