// apps/demo-svelte/app/plugin-demos/nativescript-loading-indicator.svelte
<page>
    <actionBar title="nativescript-loading-indicator" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptLoadingIndicator } from '@demo/shared';
    import { } from '@nstudio/nativescript-loading-indicator';

    let message: string = "Test nativescript-loading-indicator"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-loading-indicator.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptLoadingIndicator } from '@demo/shared';
import { } from '@nstudio/nativescript-loading-indicator';

@Component({
	selector: 'demo-nativescript-loading-indicator',
	templateUrl: 'nativescript-loading-indicator.component.html',
})
export class NativescriptLoadingIndicatorComponent {
  
  demoShared: DemoSharedNativescriptLoadingIndicator;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptLoadingIndicator();
  }

}
<ActionBar title="nativescript-loading-indicator" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-loading-indicator" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>
