// apps/demo-react/src/plugin-demos/nativescript-tracking-transparency.tsx
import * as React from "react";
import { Dialogs } from '@nativescript/core';
import { StyleSheet } from "react-nativescript";
import { DemoSharedNativescriptTrackingTransparency } from '@demo/shared';
import { } from '@nstudio/nativescript-tracking-transparency';

export function HomeScreen() {
    const demoShared = new DemoSharedNativescriptTrackingTransparency();
    return (
        <flexboxLayout style={styles.container}>
            <button
                style={styles.button}
                onTap={() => demoShared.testIt()}
            >
                Test nativescript-tracking-transparency
            </button>
        </flexboxLayout>
    );
}

const styles = StyleSheet.create({
    container: {
        height: "100%",
        flexDirection: "column",
        justifyContent: "center",
    },
    button: {
        fontSize: 24,
        color: "#2e6ddf",
    },
});

// apps/demo-angular/src/plugin-demos/nativescript-tracking-transparency.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptTrackingTransparency } from '@demo/shared';
import {} from '@nstudio/nativescript-tracking-transparency';

@Component({
	selector: 'demo-nativescript-tracking-transparency',
	templateUrl: 'nativescript-tracking-transparency.component.html',
})
export class NativescriptTrackingTransparencyComponent {
	demoShared: DemoSharedNativescriptTrackingTransparency;

	constructor(private _ngZone: NgZone) {}

	ngOnInit() {
		this.demoShared = new DemoSharedNativescriptTrackingTransparency();
	}
}

<ActionBar title="nativescript-tracking-transparency" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-tracking-transparency" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>
