// apps/demo-svelte/app/plugin-demos/nativescript-persona.svelte
<page>
    <actionBar title="nativescript-persona" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptPersona } from '@demo/shared';
    import { } from '@nstudio/nativescript-persona';

    let message: string = "Test nativescript-persona"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-persona.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptPersona } from '@demo/shared';
import { } from '@nstudio/nativescript-persona';

@Component({
	selector: 'demo-nativescript-persona',
	templateUrl: 'nativescript-persona.component.html',
})
export class NativescriptPersonaComponent {
  
  demoShared: DemoSharedNativescriptPersona;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptPersona();
  }

}
<ActionBar title="nativescript-persona" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-persona" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>
