// apps/demo-svelte/app/plugin-demos/nativescript-intercom.svelte
<page>
    <actionBar title="nativescript-intercom" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptIntercom } from '@demo/shared';
    import { } from '@nstudio/nativescript-intercom';

    let message: string = "Test nativescript-intercom"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-intercom.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptIntercom } from '@demo/shared';
import { } from '@nstudio/nativescript-intercom';

@Component({
	selector: 'demo-nativescript-intercom',
	templateUrl: 'nativescript-intercom.component.html',
})
export class NativescriptIntercomComponent {
  
  demoShared: DemoSharedNativescriptIntercom;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptIntercom();
  }

}
<ActionBar title="nativescript-intercom" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-intercom" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>
