// apps/demo-svelte/app/plugin-demos/nativescript-azure-notificationhubs.svelte
<page>
    <actionBar title="nativescript-azure-notificationhubs" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptAzureNotificationhubs } from '@demo/shared';
    import { } from '@nstudio/nativescript-azure-notificationhubs';

    let message: string = "Test nativescript-azure-notificationhubs"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-azure-notificationhubs.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptAzureNotificationhubs } from '@demo/shared';
import { } from '@nstudio/nativescript-azure-notificationhubs';

@Component({
	selector: 'demo-nativescript-azure-notificationhubs',
	templateUrl: 'nativescript-azure-notificationhubs.component.html',
})
export class NativescriptAzureNotificationhubsComponent {
  
  demoShared: DemoSharedNativescriptAzureNotificationhubs;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptAzureNotificationhubs();
  }

}
<ActionBar title="nativescript-azure-notificationhubs" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-azure-notificationhubs" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>
