// apps/demo-svelte/app/plugin-demos/nativescript-dynatrace.svelte
<page>
    <actionBar title="nativescript-dynatrace" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptDynatrace } from '@demo/shared';
    import { } from '@nstudio/nativescript-dynatrace';

    let message: string = "Test nativescript-dynatrace"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-dynatrace.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptDynatrace } from '@demo/shared';
import {} from '@nstudio/nativescript-dynatrace';

@Component({
	selector: 'demo-nativescript-dynatrace',
	templateUrl: 'nativescript-dynatrace.component.html',
})
export class DynatraceComponent {
	demoShared: DemoSharedNativescriptDynatrace;

	constructor(private _ngZone: NgZone) {}

	ngOnInit() {
		this.demoShared = new DemoSharedNativescriptDynatrace();
	}
}

<ActionBar title="nativescript-dynatrace" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test dynatrace" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>
