// apps/demo-svelte/app/plugin-demos/nativescript-airship.svelte
<page>
    <actionBar title="nativescript-airship" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptAirship } from '@demo/shared';
    import { } from '@nstudio/nativescript-airship';

    let message: string = "Test nativescript-airship"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-airship.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptAirship } from '@demo/shared';
import { } from '@nstudio/nativescript-airship';

@Component({
	selector: 'demo-nativescript-airship',
	templateUrl: 'nativescript-airship.component.html',
})
export class NativescriptAirshipComponent {
  
  demoShared: DemoSharedNativescriptAirship;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptAirship();
  }

}
<ActionBar title="nativescript-airship" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
	<ScrollView class="h-full">
		<StackLayout>
			<Button text="Test nativescript-airship" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
		</StackLayout>
	</ScrollView>
</StackLayout>
