// apps/demo-svelte/app/plugin-demos/nativescript-fullstory.svelte
<page>
    <actionBar title="nativescript-fullstory" />
    <gridLayout>
        <button class="info" text="{message}" horizontalAlignment="center" verticalAlignment="middle" textWrap="true"/>
    </gridLayout>
</page>

<script lang="typescript">
    import { DemoSharedNativescriptFullstory } from '@demo/shared';
    import { } from '@nstudio/nativescript-fullstory';

    let message: string = "Test nativescript-fullstory"
</script>

<style>
    .info {
        font-size: 20;
    }
</style>

// apps/demo-angular/src/plugin-demos/nativescript-fullstory.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedNativescriptFullstory } from '@demo/shared';
import { } from '@nstudio/nativescript-fullstory';

@Component({
	selector: 'demo-nativescript-fullstory',
	templateUrl: 'nativescript-fullstory.component.html',
})
export class NativescriptFullstoryComponent {
  
  demoShared: DemoSharedNativescriptFullstory;
  
	constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedNativescriptFullstory();
  }

}
<ActionBar title="nativescript-fullstory" class="action-bar"> </ActionBar>
<StackLayout class="p-20">
  <ScrollView class="h-full">
    <StackLayout>
      <Button text="Test nativescript-fullstory" (tap)="demoShared.testIt()" class="btn btn-primary"></Button>
    </StackLayout>
  </ScrollView>
</StackLayout>
